# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe939230cef494dcd227382628d93492793bc560ae2065e4348bcad969f58b946698f807cc413af9d8ff41182eaab2cc01aa9cfcd86fddea9d0480575b20fd2

test:
  secret_key_base: 9757fc7ada33e982b4ad82b9ab9f477f34170bcc619fbedbfc37a9cce89a7b5b86488d660581c4e8da3380e1911c81ea12227944ebe5d9acf700738ad5f30d0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
